### ISSUE TITLE
Implemented database and 

### ISSUE THREAD

**Issue by JacobTpng** [ibhattacharj/LocalVibes#37]
Implemented SQLite database with Sequelize for event data management. Backend endpoints too. Integrated front-end functionality with the backend to fetch and display event data. Included sample data.

**Comment by adrien-bekker** [comment]
Once the database and endpoints are set up I am able to start working on my feature of search results and map updating.

**Comment by adrien-bekker** [comment]
This was completed successfully with endpoints working for my feature as well
